IMAGE_NAME = "bento/ubuntu-22.04"
N = 1

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end
    
    # Definition for the controller
    config.vm.define "controller" do |controller|
        controller.vm.box = IMAGE_NAME
        controller.vm.network "private_network", ip: "192.168.56.10"

        # Port forwarding for accessing services like Grafana
        controller.vm.network "forwarded_port", guest: 32299, host: 54322

        controller.vm.hostname = "k8s-controller"
        controller.vm.provision "ansible" do |ansible|
            ansible.playbook = "roles/common/tasks/main.yml"
            ansible.extra_vars = {
                node_ip: "192.168.56.10"
            }
        end
        controller.vm.provision "ansible" do |ansible|
            ansible.playbook = "roles/master/tasks/main.yml"
            ansible.extra_vars = {
                node_ip: "192.168.56.10",
            }
        end
    end

    # Loop to create worker nodes
    (1..N).each do |i|
        config.vm.box = "ubuntu/focal64"
        config.vm.define "worker-#{i}" do |worker|
            worker.vm.box = IMAGE_NAME
            worker.vm.network "private_network", ip: "192.168.56.#{i + 10}"
            worker.vm.hostname = "worker-#{i}"
            worker.vm.provision "ansible" do |ansible|
                ansible.playbook = "roles/common/tasks/main.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.56.#{i + 10}",
                }
            end
            worker.vm.provision "ansible" do |ansible|
                ansible.playbook = "roles/worker/tasks/main.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.56.#{i + 10}",
                }
            end
        end
    end
end
