IMAGE_NAME = "ubuntu/jammy64"
N = 1

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("keys/vagrant_ssh_key.pub").first.strip
    s.inline = <<-SHELL
    echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
    end


    config.vm.provider "virtualbox" do |v|
        v.memory = 4048
        v.cpus = 2
    end

    config.vm.define "controller-1" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.56.10"

        master.vm.network "forwarded_port", guest: 6443, host: 6443



        master.vm.hostname = "controller-1"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbooks/master.yml"
            ansible.inventory_path = "inventory/hosts"
            ansible.extra_vars = {
                node_ip: "192.168.50.10",
            }
        end
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME

            node.vm.network "private_network", ip: "192.168.56.#{i + 10}"

            node.vm.hostname = "node-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "playbooks/master.yml"
                ansible.inventory_path = "inventory/hosts"
                ansible.extra_vars = {
                    node_ip: "192.168.50.#{i + 10}",
                }
            end
        end
    end
end