# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Set the SSH key insertion to false
  config.ssh.insert_key = false

  # Define the controller
  config.vm.define "controller" do |controller|
    controller.vm.box = "ubuntu/bionic64"
    controller.vm.hostname = "controller"
    controller.vm.network "private_network", ip: "192.168.56.10"
    controller.vm.provision :ansible do |ansible|
      ansible.playbook = "ansible/controller-playbook.yml"
      ansible.inventory_path = "inventory"
    end
  end

  # Define three worker machines
  (1..3).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.box = "ubuntu/bionic64"
      worker.vm.hostname = "worker#{i}"
      worker.vm.network "private_network", ip: "192.168.56.#{10 + i}"
      worker.vm.provision :ansible do |ansible|
        ansible.playbook = "ansible/worker-playbook.yml"
        ansible.inventory_path = "inventory"
      end
    end
  end

end
