{
 "title": "New Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Histogram for requests by response time",
   "type": "histogram",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by(le) (rate(backend_response_times_histogram_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average ram consumption over time in the backend",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(backend_available_ram_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response status 200 vs 400",
   "type": "piechart",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backend_total_responses{status=\"200\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "backend_total_responses{status=\"404\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}